import { contact } from '@/data/seed';
import { fmtDate, type Asset, type Certificate } from '@/lib/service/store';

/** Builds a printable calibration certificate and downloads it as an HTML file. */
export function downloadCertificate(asset: Asset, c: Certificate) {
  const html = `<!doctype html><meta charset="utf-8"><title>${c.id}</title>
<style>body{font:15px/1.5 system-ui,sans-serif;max-width:640px;margin:48px auto;color:#16232a}h1{color:#007a4d;margin:0}table{width:100%;border-collapse:collapse;margin-top:24px}td{padding:8px;border-bottom:1px solid #dde5e0}td:first-child{color:#5b6b62;width:40%}.note{margin-top:32px;font-size:12px;color:#5b6b62}</style>
<h1>Calibration certificate</h1><p>Flokefama Company Limited · ${contact.phone}</p>
<table>
<tr><td>Certificate</td><td>${c.id}</td></tr><tr><td>Date</td><td>${fmtDate(c.date)}</td></tr>
<tr><td>System</td><td>${asset.brand} ${asset.name}</td></tr><tr><td>Serial</td><td>${asset.serial}</td></tr>
<tr><td>Facility</td><td>${asset.facility}, ${asset.location}</td></tr><tr><td>Result</td><td>${c.result}</td></tr>
<tr><td>Engineer</td><td>${c.engineer}</td></tr>${c.notes ? `<tr><td>Notes</td><td>${c.notes.replace(/</g, '&lt;')}</td></tr>` : ''}
</table><p class="note">Demo certificate generated by the Flokefama service portal preview.</p>`;
  const url = URL.createObjectURL(new Blob([html], { type: 'text/html' }));
  const a = Object.assign(document.createElement('a'), { href: url, download: `${c.id}-${asset.serial}.html` });
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

