#!/usr/bin/env python3
"""Builds a tiny Flaticon UIcons bundle containing only the icons the site uses.

Scans the app source (src/**/*.ts, *.tsx) for `fi-rr-*` (regular rounded) and `fi-brands-*`
classes, subsets the official UIcons fonts to those glyphs, and writes
src/styles/uicons/{uicons.css, *.woff2}. Result: a few KB instead of ~400 KB.
Always write full class names in source (e.g. icon: 'fi-rr-microscope'), never build them
from fragments, or the scanner can't see them.

Usage:  npm run icons        (requires: pip install fonttools brotli)
Browse icons at https://www.flaticon.com/uicons (use "Regular Rounded" or "Brands").
"""
import pathlib
import re
import sys

from fontTools import subset

ROOT = pathlib.Path(__file__).resolve().parent.parent
PKG = ROOT / "node_modules/@flaticon/flaticon-uicons/css"
OUT = ROOT / "src/styles/uicons"

SETS = {
    # prefix: (css file, font family, output font name)
    "fi-rr": ("regular/rounded.css", "uicons-regular-rounded", "uicons-rr.woff2"),
    "fi-brands": ("brands/all.css", "uicons-brands", "uicons-brands.woff2"),
}

html = "\n".join(p.read_text(encoding="utf-8") for ext in ("*.ts", "*.tsx") for p in (ROOT / "src").rglob(ext))
OUT.mkdir(parents=True, exist_ok=True)
css_out = ["/* Generated by scripts/subset-icons.py. Do not edit by hand; run `npm run icons`. */"]
missing = []

for prefix, (css_file, family, font_name) in SETS.items():
    used = sorted(set(re.findall(rf"\b{prefix}-([a-z0-9-]+)", html)))
    if not used:
        continue
    source_css = (PKG / css_file).read_text(encoding="utf-8")
    font_src = re.search(r"url\(\.\./([^)]+\.woff2)\)", source_css).group(1)

    codes = {}
    for name in used:
        m = re.search(rf'\.{prefix}-{re.escape(name)}:before\{{content:"\\([0-9a-f]+)"', source_css)
        if m:
            codes[name] = m.group(1)
        else:
            missing.append(f"{prefix}-{name}")

    opts = subset.Options()
    opts.flavor = "woff2"
    opts.layout_features = []
    font = subset.load_font(str(PKG / font_src), opts)
    sub = subset.Subsetter(opts)
    sub.populate(unicodes=[int(c, 16) for c in codes.values()])
    sub.subset(font)
    subset.save_font(font, str(OUT / font_name), opts)

    css_out.append(f'@font-face{{font-family:"{family}";src:url("{font_name}") format("woff2");font-display:block}}')
    css_out.append(
        f'[class^="{prefix}-"]::before,[class*=" {prefix}-"]::before{{font-family:"{family}"!important;'
        "font-style:normal;font-weight:normal!important;line-height:1;display:inline-block;"
        "vertical-align:-.125em;-webkit-font-smoothing:antialiased}"
    )
    css_out += [f'.{prefix}-{n}::before{{content:"\\{c}"}}' for n, c in codes.items()]
    size = (OUT / font_name).stat().st_size
    print(f"{prefix}: {len(codes)} icons -> {font_name} ({size / 1024:.1f} KB)")

(OUT / "uicons.css").write_text("\n".join(css_out) + "\n", encoding="utf-8")
if missing:
    print("Unknown icon classes (check the name on flaticon.com/uicons):", ", ".join(missing))
    sys.exit(1)
