/**
 * Seed content used when Sanity is not configured (local dev, previews) and as the
 * initial import into Sanity. Everything here comes from flokefama.com as of Sep 2026
 * (product names from the 92-item shop; only a sample is seeded).
 *
 * CLIENT TO CONFIRM before launch (see docs/01-site-audit.md §5):
 *  - Product specs are marked `specsVerified: false` until checked against manufacturer datasheets.
 *  - Metrics: only figures published on the current site are used. "Hospitals served" and
 *    "Systems deployed" are wanted for the hero tracker but have no verified source yet.
 *  - A Ministry of Health partnership was proposed for the trust section; it is NOT shown until confirmed.
 */
import { catalogue } from '@/data/catalogue';
import type { Category, EventItem, Metric, Milestone, Product } from '@/lib/types';

export const categories: Category[] = [
  {
    slug: 'in-vitro-diagnostics',
    title: 'In-Vitro Diagnostics',
    short: 'IVD',
    description: 'Biochemistry and haematology analysers with matched reagents and controls.',
    icon: 'fi-rr-microscope',
    image: '/images/products/auto-haematology-analyzer-bc3000plus.webp',
  },
  {
    slug: 'critical-care',
    title: 'Patient Monitoring & Critical Care',
    short: 'Critical care',
    description: 'Monitors, defibrillators, CTG and respiratory support for wards and theatres.',
    icon: 'fi-rr-heart-rate',
    image: '/images/products/patient-monitor-comen.webp',
  },
  {
    slug: 'laboratory',
    title: 'Laboratory Equipment',
    short: 'Laboratory',
    description: 'Microscopy, centrifugation and the everyday instruments of a modern lab.',
    icon: 'fi-rr-flask-gear',
    image: '/images/products/microscope-olympus-cx23.webp',
  },
  {
    slug: 'hospital-equipment',
    title: 'Hospital Equipment & Furniture',
    short: 'Hospital',
    description: 'Sterilisation, suction, beds and clinical furniture built for daily use.',
    icon: 'fi-rr-hospital',
    image: '/images/products/examination-bed.webp',
  },
  {
    slug: 'consumables',
    title: 'Consumables & Reagents',
    short: 'Consumables',
    description: 'A continuous, reliable supply of reagents, cuvettes and disposables.',
    icon: 'fi-rr-syringe',
    image: '/images/products/ba-88a-bulb.webp',
  },
];

/** The company brochure from flokefama.com (FlokeBroucher.pdf), re-saved at web size. */
export const brochureUrl = '/brochure/flokefama-brochure.pdf';

/** The full catalogue from the current flokefama.com shop (src/data/catalogue.ts, generated by the import). */
export const products: Product[] = catalogue;

/** "The Results" counters and figures, as published on flokefama.com (home, contact and awards pages). */
export const metrics: Metric[] = [
  { label: 'Hospitals, medical laboratories served and counting', value: 700, suffix: '+' },
  { label: 'Successful system integrations', value: 300, suffix: '+' },
  { label: 'Branches', value: 6, caption: 'Santa Maria, Korle-bu, Okaishie, Kumasi, Aflao, Techiman' },
  { label: 'Talented team members', value: 40 },
]

/** Figures shown with “Industry Experience” on the current About page. */
export const experienceFigures: Metric[] = [
  { label: 'Years of Experience', value: 17 },
  { label: 'Satisfied Clients', value: 56 },
];

/** Secondary figures from the current Awards page (its "5 Awards" is left out: the gallery shows all five). */
export const companyFigures: Metric[] = [
  { label: 'Health products', value: 200 },
  { label: 'Team members', value: 40 },
];

export const milestones: Milestone[] = [
  {
    id: 'mindray-ivd-2026',
    kicker: 'Award · March 2026',
    title: 'Best in In-Vitro Diagnostics',
    body: 'Breakthrough Award and Best in IVD at the Mindray Central Africa Region awards, Nairobi.',
    date: '2026-03-13',
    image: '/images/mindray-award.webp',
    icon: 'fi-rr-trophy',
  },
  {
    id: 'ghana-club-100',
    kicker: 'Ranking',
    title: 'Ghana Club 100',
    body: 'Recognised among the leading companies in Ghana.',
    icon: 'fi-rr-award',
  },
  {
    id: 'forbes-africa-2026',
    kicker: 'Press · June/July 2026',
    title: 'Featured in Forbes Africa',
    body: '“Ghana: Africa Undiscovered” edition, in collaboration with Penresa.',
    date: '2026-07-31',
    icon: 'fi-rr-star',
  },
  {
    id: 'university-of-ghana',
    kicker: 'Partnership · March 2026',
    title: 'University of Ghana',
    body: 'Shaping the next generation of biomedical engineers with the School of Engineering.',
    date: '2026-03-18',
    icon: 'fi-rr-graduation-cap',
  },
];

export const distributors = ['Mindray', 'Biozek Holland', 'MR Global'];

/** Technology partners (manufacturers Flokefama officially distributes). */
export const technologyPartners = [
  { name: 'Mindray', logo: '/images/partners/mindray.webp', w: 800, h: 190, role: 'Official distributor' },
  { name: 'Biozek Holland', logo: '/images/partners/biozek.webp', w: 600, h: 160, role: 'Official distributor' },
  { name: 'MR Global', logo: null, w: 0, h: 0, role: 'Official distributor' },
];

/** Clientele shown on the current flokefama.com "Our Partners & Clientele" strip. */
export const clients = [
  { name: 'The Trust Hospital', logo: '/images/partners/trust-hospital.webp', w: 320, h: 134 },
  { name: 'Korle Bu Teaching Hospital', logo: '/images/partners/korle-bu.webp', w: 800, h: 763 },
  { name: 'Komfo Anokye Teaching Hospital', logo: '/images/partners/kath.webp', w: 512, h: 512 },
  { name: 'University of Ghana Medical Centre', logo: '/images/partners/ugmc.webp', w: 800, h: 468 },
  { name: 'Euracare', logo: '/images/partners/euracare.webp', w: 218, h: 50 },
  { name: 'LEKMA Hospital', logo: '/images/partners/lekma.webp', w: 267, h: 335 },
];

export const branches = [
  { name: 'Santa Maria', detail: 'Flokefama Company Ltd. Head Office' },
  { name: 'Korle-bu', detail: 'Opposite Main Korle-bu Teaching Hospital' },
  { name: 'Okaishie', detail: 'Adepa Building, Ground Floor' },
  { name: 'Kumasi', detail: 'Kwadaso Estate' },
  { name: 'Aflao', detail: '200 metres From Makavo Junction' },
  { name: 'Techiman', detail: 'Near Melcom Techiman' },
]

export const contact = {
  address: 'Flokefama Company Limited, Santa Maria, Accra, Ghana',
  /** Head office coordinates, from the map on the current Contact page. */
  lat: 5.5966475,
  lng: -0.2732217,
  phone: '+233 53 339 2863',
  phoneHref: 'tel:+233533392863',
  whatsapp: 'https://wa.me/233533392863',
  info: 'info@flokefama.com',
  sales: 'sales@flokefama.com',
  support: 'support@flokefama.com',
};

export const maps = {
  embed: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3970.621062634358!2d-0.27322170000000003!3d5.5966475!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xfdf996210a66e9f%3A0xcc9653b8022f3b8d!2sFlokefama%20Company%20Limited!5e0!3m2!1sen!2sgh!4v1700000000000!5m2!1sen!2sgh',
  directions: `https://www.google.com/maps/dir/?api=1&destination=${contact.lat},${contact.lng}&travelmode=driving`,
  open: `https://www.google.com/maps/search/?api=1&query=${contact.lat},${contact.lng}`,
};

/** Testimonials, verbatim from the current home and About pages. */
export const testimonials = [
  {
    quote: 'Flokefama has been our go-to supplier for medical equipment, and they never disappoint. Their products are top-notch, and their customer service is exceptional. Highly recommended!',
    name: 'Dr. Kwame Asante',
    role: 'Medical Director, Lifecare Hospital',
  },
  {
    quote: 'We urgently needed diagnostic tools for our clinic, and Flokefama delivered right on time. Their team provided excellent after-sales support, ensuring everything was set up correctly.',
    name: 'Patricia Osei',
    role: 'Clinic Administrator',
  },
  {
    quote: 'Flokefama has been instrumental in equipping our laboratory with state-of-the-art devices. Their expertise and product recommendations have improved our efficiency significantly.',
    name: 'Dr. Nana Kusi',
    role: 'Lab Scientist',
  },
];

/** Core values, from the current About page. */
export const coreValues = [
  { title: 'Honesty', icon: 'fi-rr-handshake', text: 'Being transparent and truthful in all business dealings, ensuring clear communication and setting realistic expectations. We build trust through reliability, consistently delivering what we promise.' },
  { title: 'Integrity', icon: 'fi-rr-balance-scale-left', text: 'Upholding strong ethical standards and maintaining consistency in quality and service. We demonstrate timeliness by ensuring prompt delivery, meeting deadlines, and responding swiftly to customer needs.' },
  { title: 'Innovation', icon: 'fi-rr-lightbulb-on', text: 'Continuously improving and embracing new ideas, technologies, and solutions to enhance efficiency and meet evolving needs. Our commitment to innovation drives unmatched customer service, providing clients with cutting-edge solutions and exceptional support.' },
  { title: 'Respect', icon: 'fi-rr-hands-heart', text: 'Valuing people by fostering professionalism, inclusivity, and strong relationships. We uphold unmatched customer service by treating every client, partner, and team member with care, attentiveness, and responsiveness.' },
] as const;

/** Services, as listed on the current Services and About pages. */
export const serviceList = [
  { icon: 'fi-rr-box-open', title: 'Medical Equipment Sales', body: 'We supply a wide range of high-quality medical equipment to meet the diverse needs of hospitals, clinics, and laboratories.' },
  { icon: 'fi-rr-settings', title: 'Equipment Installation & Commissioning', body: 'Ensuring proper installation and setup is crucial for the efficiency and longevity of medical equipment. Seamless setup and optimal functionality.' },
  { icon: 'fi-rr-shield-check', title: 'Technical Support & Equipment Maintenance', body: 'To ensure continuous, uninterrupted operation: regular maintenance to keep equipment in peak condition, minimizing downtime.' },
  { icon: 'fi-rr-chart-line-up', title: 'Calibration Services', body: 'Accuracy is critical in medical diagnostics and treatment. Precise calibration for accuracy and reliability.' },
  { icon: 'fi-rr-tool-box', title: 'Equipment Repairs & Spare Parts Supply', body: 'Medical equipment is a major investment, and breakdowns can significantly impact healthcare delivery. Efficient repair services to minimize operational disruptions.' },
  { icon: 'fi-rr-graduation-cap', title: 'Training & Capacity Building', body: 'We believe in empowering healthcare professionals with the knowledge and skills they need to operate medical equipment effectively. Comprehensive programs and ongoing support to optimize equipment utilization.' },
] as const;

/** "Our Services" on the current About page: the six services in one line each. */
export const servicesInBrief = [
  { icon: 'fi-rr-box-open', title: 'Medical Equipment Sales', text: 'Providing top-of-the-line medical equipment to meet diverse healthcare needs.' },
  { icon: 'fi-rr-settings', title: 'Equipment Installation', text: 'Ensuring seamless setup and optimal functionality.' },
  { icon: 'fi-rr-shield-check', title: 'Equipment Maintenance', text: 'Regular maintenance to keep equipment in peak condition, minimizing downtime.' },
  { icon: 'fi-rr-tool-box', title: 'Equipment Repairs', text: 'Efficient repair services to minimize operational disruptions.' },
  { icon: 'fi-rr-chart-line-up', title: 'Calibration Services', text: 'Precise calibration for accuracy and reliability.' },
  { icon: 'fi-rr-graduation-cap', title: 'Training and Support', text: 'Comprehensive programs and ongoing support to optimize equipment utilization.' },
] as const;

/** "Why choose Flokefama?", from the current Services page. */
export const whyChoose = [
  { icon: 'fi-rr-link-alt', title: 'End-to-end solutions', body: 'From procurement and installation to training and maintenance.' },
  { icon: 'fi-rr-globe', title: 'High-quality, globally recognized medical brands', body: 'We are the Official distributor of Mindray, Biozek Holland, and MR Global.' },
  { icon: 'fi-rr-headset', title: 'Reliable after-sales support', body: 'Reliable after-sales support and rapid response service.' },
  { icon: 'fi-rr-marker', title: 'Nationwide reach', body: 'Branches in Santa Maria, Korle-bu, Okaishie, Kumasi, Aflao and Techiman.' },
] as const;

/** Awards shown on the current Awards page (photos of the actual awards) and in the Media Centre. */
export const awards = [
  {
    id: 'gc100-healthcare',
    title: 'No.1 company in the Healthcare sector',
    body: 'Ranked 1st in the Healthcare sector at the 21st edition of the Ghana Club 100 Awards, Ghana Investment Promotion Centre.',
    year: '2024',
    image: '/images/awards/ghana-club-100-healthcare.webp',
    alt: 'Ghana Investment Promotion Centre certificate ranking Flokefama 1st in the Healthcare sector, Ghana Club 100',
  },
  {
    id: 'gc100',
    title: 'Ghana Club 100',
    body: 'Ranked No. 49 among Ghana’s top companies, 21st edition of the Ghana Club 100.',
    year: '2024',
    image: '/images/awards/ghana-club-100-trophy.webp',
    alt: 'Ghana Club 100 21st edition trophy awarded to Flokefama Company Limited',
  },
  {
    id: 'mindray-2024',
    title: 'Mindray Market Breakthrough Award',
    body: 'Presented by Shenzhen Mindray Bio-Medical Electronics to Flokefama Company Limited.',
    year: '2024',
    image: '/images/awards/mindray-breakthrough-2024.webp',
    alt: 'Mindray 2024 Market Breakthrough Award trophy',
  },
  {
    id: 'emy-2024',
    title: 'Man of the Year, Health',
    body: 'Conferred on Emmanuel Teye Kwabena Kenney at the 9th annual EMY Africa Awards, Accra, 24 November 2024.',
    year: '2024',
    image: '/images/awards/emy-africa-2024.webp',
    alt: 'EMY Africa Awards certificate: Man of the Year, Health',
  },
  {
    id: 'mindray-ivd-2026',
    title: 'Breakthrough Award & Best in IVD',
    body: 'Mindray Central Africa Region awards, JW Marriott, Nairobi.',
    year: '2026',
    image: '/images/mindray-award.webp',
    alt: 'The Flokefama team receiving the Mindray IVD awards on stage in Nairobi',
  },
];

/** Events & Activities (the current site lists past events only). */
export const events: EventItem[] = [
  {
    id: 'floke-praise-2026',
    title: 'Floke Praise 2026',
    date: '2026-10-24',
    start: '2026-10-24T15:00:00Z', // Ghana is on GMT all year
    end: '2026-10-24T19:00:00Z', // for calendar invites only; the flyer gives a start time
    time: '3:00 pm',
    venue: 'Flokefama Company Limited, Head Office, Kwashieman',
    theme: 'Grounded in Gratitude, Driven by Purpose.',
    guests: 'Perez Music & other guest ministers',
    body: 'Floke Praise 2026 is here. Let’s celebrate God together.',
    /** The event flyer, as shared by Flokefama. */
    image: '/images/event-floke-praise-2026.webp',
    imageWidth: 1170,
    imageHeight: 1450,
    alt: 'Floke Praise 2026 flyer: Perez Music and other guest ministers, 24 October 2026 at 3:00 pm, Flokefama head office, Kwashieman. Theme: Grounded in gratitude, driven by purpose.',
  },
  {
    id: 'floke-praise-2025',
    title: 'Floke Praise 2025 – Celebrating 17 Years of Saving Lives!',
    date: '2025-10-18',
    start: '2025-10-18T15:00:00Z',
    end: '2025-10-18T19:00:00Z',
    time: '3:00 pm – 7:00 pm',
    venue: 'Flokefama Company Limited, 2 Regy St., Accra',
    guests: 'Uncle Ato and MOG Music',
    body: 'Join us for an evening of gratitude, worship, and celebration as Flokefama Company Ltd marks 17 years of saving lives and serving communities with excellence in healthcare.',
    more: [
      'This year’s edition, themed “Celebrating 17 Years of Saving Lives,” brings together the entire Flokefama family, partners, and friends to lift our voices in thanksgiving for how far we’ve come — and to rededicate ourselves to our purpose of service, compassion, and innovation in healthcare.',
      'Expect an atmosphere filled with praise, joy, and inspiration as we host two of Ghana’s most anointed gospel ministers — Uncle Ato and MOG Music — leading us in spirit-filled worship.',
    ],
    price: 'Free',
    /** The event flyer, from the current site's Events page. */
    image: '/images/event-floke-praise-2025.webp',
    imageWidth: 1400,
    imageHeight: 788,
    alt: 'Floke Praise 2025 flyer: celebrating 17 years of saving lives, 18 October, 3:00 pm to 7:00 pm, Flokefama head office, Santa Maria, with guest artists Uncle Ato and MOG',
  },
];

/** Company statements, verbatim in substance from the current "About us" page. */
export const purpose = [
  { label: 'Mission', icon: 'fi-rr-bullseye', text: 'To provide world class medical solutions to all medical facilities and laboratories in the West African sub region.' },
  { label: 'Vision', icon: 'fi-rr-eye', text: 'To have a localized industrial complex which produces all medical equipment and reagents locally and to be listed on the Ghana Stock Exchange by 2030.' },
  { label: 'Aim', icon: 'fi-rr-flask-gear', text: 'To have a production plant in Ghana to produce our reagents and some of our hospital disposables locally to boost the economy and create meaningful well paying jobs.' },
] as const;


